### PR TITLE
Bootstrap v5, React bootstrap v2, React 18, Redux and Misc. Npm Packages Upgrade

### PR DESCRIPTION
**Pull request by Onurcankaratay**
This pull request primarily addresses the transition from React 17 to React 18, while also including updates for Redux, Auth0, and other third-party integrations heavily used in the portal, ensuring compatibility with React 18.

Ticket:  [Trello 1](https://trello.com/c/Y77EYoZP/331-react-18-and-react-bootstrap-v2-upgrades-for-cgap) & [Trello 2](https://trello.com/c/vl9gUppW/344-fix-deprecated-scss-features)
Related PR:  [SPC](https://github.com/4dn-dcic/shared-portal-components/pull/261)

### Updates
- **React**: Upgraded from v17 to v18
- **Redux**: Updated from v4 to v5
- **Auth0-Lock**: Upgraded from v11 to v12
- **Gulp.js**: Updated from v4 to v5

Additionally, this pull request implements the migration to Bootstrap v5 and updates to React-Bootstrap v2, ensuring that styles and components are fully compatible with the latest standards.

- **Bootstrap v5 Migration**: Adapted styles and class names to align with Bootstrap 5.
- **React-Bootstrap v2 Update**: Updated components and class names to conform to React-Bootstrap 2 standards.
- **Cypress Test Refactoring**: Revised test cases to reflect changes in class names, ensuring comprehensive testing post-migration.
- **FontAwesome v6 Integration**: Upgraded to FontAwesome v6 to resolve console SCSS build warnings and ensure future compatibility.

### CODE REVIEW

**Comment by Onurcankaratay** [comment]
[React 18 and react-bootstrap v2 upgrades for CGAP](https://trello.com/c/Y77EYoZP/331-react-18-and-react-bootstrap-v2-upgrades-for-cgap)

**Comment by Onurcankaratay** [comment]
[Node.js v20+ upgrade for CGAP](https://trello.com/c/LPfsXT67/332-nodejs-v20-upgrade-for-cgap)

**Comment by Onurcankaratay** [comment]
[Fix deprecated scss features](https://trello.com/c/vl9gUppW/344-fix-deprecated-scss-features)

**Review by Bianca-Morris — COMMENTED** [review]
Finally got around to looking at this. Code looks good aside from one minor detail I mentioned that might be worth backtracking on. I haven't been able to test this locally, however, as my CGAP local env is giving me a bit of trouble at the moment, and I haven't had time to fix it. Could you deploy this to wolf sometime soon and let us know? There are a few final things I want to double check and then this can be merged.

**Comment by utku-ozturk** [comment]
@Bianca-Morris no worries, thanks for the review. It is recently available in cgap-wolf. AFAIK, SPC's release was changed from beta to production. Anyway, we'll redeploy it and keep you posted. 

> Finally got around to looking at this. Code looks good aside from one minor detail I mentioned that might be worth backtracking on. I haven't been able to test this locally, however, as my CGAP local env is giving me a bit of trouble at the moment, and I haven't had time to fix it. Could you deploy this to wolf sometime soon and let us know? There are a few final things I want to double check and then this can be merged.

**Comment by utku-ozturk** [comment]
@Bianca-Morris FYI, recent version is available in https://cgap-wolf.hms.harvard.edu

**Review by crfmc — APPROVED** [review]

**Review by utku-ozturk — APPROVED** [review]

**Pull request merged**
