### PR TITLE
Remove some unused/vulnerable NPM packages

### PR DESCRIPTION
**Pull request by alexkb0009**
PR in response to `npm audit` -

Removed:
- esdoc (not used in years, never finished, no new versions in years)
- uglifyjs (not used since webpack upgrade, has vulnerabilities)

### CODE REVIEW

**Review by utku-ozturk — APPROVED** [review]
I have tested locally. works, and looks great!

**Review by Bianca-Morris — COMMENTED** [review]
As a heads up, I would delete `node_modules` and re-install everything again once more and commit that to master, because it looks like there's an edit in `package-lock.json` that isn't included here:
```
"tr46": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/tr46/-/tr46-1.0.1.tgz",
      "integrity": "sha1-qLE/1r/SSJUZZ0zN5VujaTtwbQk=",
      "dev": true,
      "requires": {
        "punycode": "^2.1.0"
      },
      "dependencies": {
        "punycode": {
          "version": "2.1.1",
          "resolved": "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz",
          "integrity": "sha512-XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==",
          "dev": true
        }
      }
    },
```

Would also be good to bump the version (if nothing else has been merged to master yet) so we know if there are any issues that arise as a result of any of these changes.

**Comment by alexkb0009** [comment]
"tr46" appears to be a subdependency of jest-cli and jsdom (if do `npm ls tr46` it should show what it used by; it's brought up to top-level of package-lock.json by `npm dedupe` (& maybe during `npm install`, also) when multiple packages share same dependency.

**Comment by alexkb0009** [comment]
Will look into a tiny bit more and possibly push the package-lock.json version with punycode in it. It doesn't/didn't seem to affect any app code when ran, and the packages that depend on tr46 are in `devDependencies`, so hopefully not super urgent...

**Pull request merged**
